In [42]:
print ("Instalando as bibliotecas do projeto...")
!pip install pandas openpyxl folium matplotlib seaborn

Instalando as bibliotecas do projeto...
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in C:\Users\linco\AppData\Roaming\Python\Python314\site-packages (3.0.3)
Requirement already satisfied: openpyxl in C:\Users\linco\AppData\Roaming\Python\Python314\site-packages (3.1.5)
Requirement already satisfied: folium in C:\Users\linco\AppData\Roaming\Python\Python314\site-packages (0.20.0)
Requirement already satisfied: matplotlib in C:\Users\linco\AppData\Roaming\Python\Python314\site-packages (3.11.0)
Requirement already satisfied: seaborn in C:\Users\linco\AppData\Roaming\Python\Python314\site-packages (0.13.2)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\linco\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\linco\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\linco\AppData\Roaming\Python\Python314\site-packages (from pandas) (2026.2)
Requirement already satisfied: et-xmlfile in C:\Users\linco\AppData\Roaming\Python\Python314\site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: branca>=0.6.0 in C:\Users\linco\AppData\Roaming\Python\Python314\site-packages (from folium) (0.8.2)
Requirement already satisfied: jinja2>=2.9 in C:\Users\linco\AppData\Roaming\Python\Python314\site-packages (from folium) (3.1.6)
Requirement already satisfied: requests in C:\Users\linco\AppData\Roaming\Python\Python314\site-packages (from folium) (2.34.2)
Requirement already satisfied: xyzservices in C:\Users\linco\AppData\Roaming\Python\Python314\site-packages (from folium) (2026.3.0)
Requirement already satisfied: contourpy>=1.0.1 in C:\Users\linco\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in C:\Users\linco\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in C:\Users\linco\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\Users\linco\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in C:\Users\linco\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=9 in C:\Users\linco\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (12.3.0)
Requirement already satisfied: pyparsing>=3 in C:\Users\linco\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: MarkupSafe>=2.0 in C:\Users\linco\AppData\Roaming\Python\Python314\site-packages (from jinja2>=2.9->folium) (3.0.3)
Requirement already satisfied: six>=1.5 in C:\Users\linco\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\linco\AppData\Roaming\Python\Python314\site-packages (from requests->folium) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\linco\AppData\Roaming\Python\Python314\site-packages (from requests->folium) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\linco\AppData\Roaming\Python\Python314\site-packages (from requests->folium) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in C:\Users\linco\AppData\Roaming\Python\Python314\site-packages (from requests->folium) (2026.6.17)

In [43]:
import pandas as pd

#Carregando o arquivo excel com os dados de furtos e roubos
df = pd.read_excel('VeiculosSubtraidos_2026.xlsx', sheet_name=2)

#Exibindo as colunas do dataframe
print("Colunas selecionadas no arquivo excel:")
print(df.columns.tolist())

df.head()

Colunas selecionadas no arquivo excel:
['ID_DELEGACIA', 'NOME_DEPARTAMENTO', 'NOME_SECCIONAL', 'NOME_DELEGACIA', 'NOME_MUNICIPIO', 'ANO_BO', 'NUM_BO', 'VERSAO', 'NOME_DEPARTAMENTO_CIRC', 'NOME_SECCIONAL_CIRC', 'NOME_DELEGACIA_CIRC', 'NOME_MUNICIPIO_CIRC', 'DATA_OCORRENCIA_BO', 'HORA_OCORRENCIA', 'DESCRICAO_APRESENTACAO', 'DATAHORA_REGISTRO_BO', 'DATA_COMUNICACAO_BO', 'DATAHORA_IMPRESSAO_BO', 'DESCR_PERIODO', 'AUTORIA_BO', 'FLAG_INTOLERANCIA', 'TIPO_INTOLERANCIA', 'FLAG_FLAGRANTE', 'FLAG_STATUS', 'DESC_LEI', 'FLAG_ATO_INFRACIONAL', 'RUBRICA', 'DESCR_CONDUTA', 'DESDOBRAMENTO', 'CIRCUNSTANCIA', 'DESCR_TIPOLOCAL', 'DESCR_SUBTIPOLOCAL', 'CIDADE', 'BAIRRO', 'CEP', 'DESC_NATUREZA_LOCAL', 'LOGRADOURO_VERSAO', 'LOGRADOURO', 'NUMERO_LOGRADOURO', 'LATITUDE', 'LONGITUDE', 'CONT_VEICULO', 'DESCR_OCORRENCIA_VEICULO', 'DESCR_TIPO_VEICULO', 'DESCR_MARCA_VEICULO', 'ANO_FABRICACAO', 'ANO_MODELO', 'PLACA_VEICULO', 'DESC_COR_VEICULO', 'MES_REGISTRO_BO', 'ANO_REGISTRO_BO', 'CMD', 'BTL', 'CIA', 'COD IBGE']

,ID_DELEGACIA,NOME_DEPARTAMENTO,NOME_SECCIONAL,NOME_DELEGACIA,NOME_MUNICIPIO,ANO_BO,NUM_BO,VERSAO,NOME_DEPARTAMENTO_CIRC,NOME_SECCIONAL_CIRC,...,ANO_FABRICACAO,ANO_MODELO,PLACA_VEICULO,DESC_COR_VEICULO,MES_REGISTRO_BO,ANO_REGISTRO_BO,CMD,BTL,CIA,COD IBGE
0,10108,DECAP,DEL.SEC.1º CENTRO,08º D.P. BRAS,S.PAULO,2026,AB9927,2,DECAP,DEL.SEC.1º CENTRO,...,2000.0,2001.0,DAD4B85,Prata,1,2026,CPA/M-1,7ºBPM/M,3ªCIA_4ªCIA,3550308
1,10108,DECAP,DEL.SEC.1º CENTRO,08º D.P. BRAS,S.PAULO,2026,AB9927,2,DECAP,DEL.SEC.1º CENTRO,...,2000.0,2001.0,DAD4B85,Prata,1,2026,CPA/M-1,7ºBPM/M,3ªCIA_4ªCIA,3550308
2,10108,DECAP,DEL.SEC.1º CENTRO,08º D.P. BRAS,S.PAULO,2026,AB9927,2,DECAP,DEL.SEC.1º CENTRO,...,2000.0,2001.0,DAD4B85,Prata,1,2026,CPA/M-1,7ºBPM/M,3ªCIA_4ªCIA,3550308
3,10108,DECAP,DEL.SEC.1º CENTRO,08º D.P. BRAS,S.PAULO,2026,AB9927,2,DECAP,DEL.SEC.1º CENTRO,...,2000.0,2001.0,DAD4B85,Prata,1,2026,CPA/M-1,7ºBPM/M,3ªCIA_4ªCIA,3550308
4,10101,DECAP,DEL.SEC.1º CENTRO,01º D.P. SE,S.PAULO,2026,AF6118,1,DECAP,DEL.SEC.1º CENTRO,...,2021.0,2022.0,RMR5J35,Vermelho,1,2026,CPA/M-1,7ºBPM/M,3ªCIA_4ªCIA,3550308

In [44]:
import pandas as pd

# Carregando o arquivo Excel
df = pd.read_excel('VeiculosSubtraidos_2026.xlsx', sheet_name=2)

# Selecionando colunas desejadas
df_selecionado = df[['RUBRICA', 'DESCR_TIPO_VEICULO', 'DATA_OCORRENCIA_BO',
                  'HORA_OCORRENCIA', 'LATITUDE', 'LONGITUDE']]

df_selecionado.head ()

,RUBRICA,DESCR_TIPO_VEICULO,DATA_OCORRENCIA_BO,HORA_OCORRENCIA,LATITUDE,LONGITUDE
0,Localização/Apreensão de veículo,Automovel,2026-01-03,09:50:00,-23.554290,-46.631983
1,Adulteração de sinal identificador de veículo ...,Automovel,2026-01-03,09:50:00,-23.554290,-46.631983
2,Localização/Apreensão e Entrega de veículo,Automovel,2026-01-03,09:50:00,-23.554290,-46.631983
3,Receptação (art. 180),Automovel,2026-01-03,09:50:00,-23.554290,-46.631983
4,Localização/Apreensão e Entrega de veículo,Automovel,2026-01-06,NaN,-23.545789,-46.634343

In [ ]:
#Estabelecendo filtro para apenas linhas que contém "Furto" na coluna "RUBRICA"
filtro_furtos = df_selecionado['RUBRICA'].str.contains('Furto', case=False, na=False)

#Estabelecendo filtro para apenas categoria de "Motociclos" na coluna "DESCR_TIPO_VEICULO"
filtro_motos = df_selecionado['DESCR_TIPO_VEICULO'].str.contains('^Moto', case=False, na=False)

#Aplicando os dois filtros juntos
df_filtrado = df_selecionado[filtro_furtos & filtro_motos].copy()

#Mostrando o tamanho da base de dados que iremos utilizar
print(f"Registro de furtos a motos, com coordenadas: {len(df_filtrado)}")

#Exibindo os dados filtrados
df_filtrado.head()

Registro de furtos a motos, com coordenadas: 12791